source 'https://git.coding.net/CocoaPods/Specs.git'
source 'https://github.com/AnyaDeng/DXJSpecs.git'
use_frameworks!

platform :ios, '8.0'

target 'DXJCategoryKit_Example' do
  pod 'DXJCategoryKit', :path => '../'
  pod 'DXJTools', '~> 1.0.3'
  
  target 'DXJCategoryKit_Tests' do
    inherit! :search_paths

    
  end
end
